<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html lang="">
	<jsp:include page="header.jsp">
		<jsp:param value="Plattegrond" name="title"/>
		<jsp:param value="Plattegrond jobbeurs" name="h2"/>
	</jsp:include>
	
	
	<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="img/Standplaatsen jobbeurs 2016-bedrijven-def-1.png" usemap="#image-map">

<map name="image-map">
    <area  alt="64" title="64" href="Controller?action=showopt&id=64" coords="613,922,536,876" shape="rect">
    <area  alt="63" title="63" href="Controller?action=showopt&id=63" coords="615,872,689,922" shape="rect">
    <area  alt="62" title="62" href="Controller?action=showopt&id=62" coords="699,876,747,944" shape="rect">
    <area  alt="61" title="61" href="Controller?action=showopt&id=61" coords="697,951,749,1019" shape="rect">
    <area  alt="60" title="60" href="Controller?action=showopt&id=60" coords="726,1025,801,1070" shape="rect">
    <area  alt="59" title="59" href="Controller?action=showopt&id=59" coords="803,1025,873,1070" shape="rect">
    <area  alt="58" title="58" href="Controller?action=showopt&id=58" coords="879,1025,953,1068" shape="rect">
    <area  alt="57" title="57" href="Controller?action=showopt&id=57" coords="953,1027,1026,1068" shape="rect">
    <area  alt="56" title="56" href="Controller?action=showopt&id=56" coords="1026,953,1073,1019" shape="rect">
    <area  alt="55" title="55" href="Controller?action=showopt&id=55" coords="1024,876,1077,946" shape="rect">
    <area  alt="54" title="54" href="Controller?action=showopt&id=54" coords="1077,880,1156,927" shape="rect">
    <area  alt="53" title="53" href="Controller?action=showopt&id=53" coords="1160,880,1242,928" shape="rect">
    <area  alt="52" title="52" href="Controller?action=showopt&id=52" coords="1282,880,1364,926" shape="rect">
    <area  alt="51" title="51" href="Controller?action=showopt&id=51" coords="1368,878,1447,924" shape="rect">
    <area  alt="50" title="50" href="Controller?action=showopt&id=50" coords="1449,876,1531,926" shape="rect">
    <area  alt="49" title="49" href="Controller?action=showopt&id=49" coords="1490,780,1562,829" shape="rect">
    <area  alt="48" title="48" href="Controller?action=showopt&id=48" coords="1414,782,1490,829" shape="rect">
    <area  alt="47" title="47" href="Controller?action=showopt&id=47" coords="1341,780,1414,833" shape="rect">
    <area  alt="46" title="46" href="Controller?action=showopt&id=46" coords="1267,783,1335,834" shape="rect">
    <area  alt="45" title="45" href="Controller?action=showopt&id=45" coords="1193,780,1261,832" shape="rect">
    <area  alt="44" title="44" href="Controller?action=showopt&id=44" coords="1112,783,1187,832" shape="rect">
    <area  alt="43" title="43" href="Controller?action=showopt&id=43" coords="988,783,1061,830" shape="rect">
    <area  alt="42" title="42" href="Controller?action=showopt&id=42" coords="912,780,984,828" shape="rect">
    <area  alt="41" title="41" href="Controller?action=showopt&id=41" coords="838,780,908,828" shape="rect">
    <area  alt="40" title="40" href="Controller?action=showopt&id=40" coords="763,780,834,828" shape="rect">
    <area  alt="39" title="39" href="Controller?action=showopt&id=39" coords="685,780,759,829" shape="rect">
    <area  alt="38" title="38" href="Controller?action=showopt&id=38" coords="615,778,683,832" shape="rect">
    <area  alt="37" title="37" href="Controller?action=showopt&id=37" coords="613,714,685,763" shape="rect">
    <area  alt="36" title="36" href="Controller?action=showopt&id=36" coords="689,713,763,761" shape="rect">
    <area  alt="35" title="35" href="Controller?action=showopt&id=35" coords="765,714,836,763" shape="rect">
    <area  alt="34" title="34" href="Controller?action=showopt&id=34" coords="840,712,912,764" shape="rect">
    <area  alt="33" title="33" href="Controller?action=showopt&id=33" coords="914,714,984,762" shape="rect">
    <area  alt="32" title="32" href="Controller?action=showopt&id=32" coords="988,712,1061,763" shape="rect">
    <area  alt="31" title="31" href="Controller?action=showopt&id=31" coords="1114,714,1187,761" shape="rect">
    <area  alt="30" title="30" href="Controller?action=showopt&id=30" coords="1189,714,1263,762" shape="rect">
    <area  alt="29" title="29" href="Controller?action=showopt&id=29" coords="1263,714,1337,763" shape="rect">
    <area  alt="28" title="28" href="Controller?action=showopt&id=28" coords="1341,714,1412,763" shape="rect">
    <area  alt="27" title="27" href="Controller?action=showopt&id=27" coords="1416,713,1486,761" shape="rect">
    <area  alt="26" title="26" href="Controller?action=showopt&id=26" coords="1488,713,1564,763" shape="rect">
    <area  alt="25" title="25" href="Controller?action=showopt&id=25" coords="1261,609,1333,656" shape="rect">
    <area  alt="24" title="24" href="Controller?action=showopt&id=24" coords="1187,606,1257,659" shape="rect">
    <area  alt="23" title="23" href="Controller?action=showopt&id=23" coords="1110,605,1183,654" shape="rect">
    <area  alt="22" title="22" href="Controller?action=showopt&id=22" coords="1001,607,1075,657" shape="rect">
    <area  alt="21" title="21" href="Controller?action=showopt&id=21" coords="922,609,997,654" shape="rect">
    <area  alt="20" title="20" href="Controller?action=showopt&id=20" coords="848,606,920,658" shape="rect">
    <area  alt="19" title="19" href="Controller?action=showopt&id=19" coords="1723,839,1775,907" shape="rect">
    <area  alt="18" title="18" href="Controller?action=showopt&id=18" coords="1721,762,1779,834" shape="rect">
    <area  alt="17" title="17" href="Controller?action=showopt&id=17" coords="435,770,491,842" shape="rect">
    <area  alt="12" title="12" href="Controller?action=showopt&id=12" coords="759,565,809,635" shape="rect">
    <area  alt="11" title="11" href="Controller?action=showopt&id=11" coords="875,512,951,563" shape="rect">
    <area  alt="10" title="10" href="Controller?action=showopt&id=10" coords="953,514,1024,565" shape="rect">
    <area  alt="9" title="9" href="Controller?action=showopt&id=9" coords="1028,513,1098,562" shape="rect">
    <area  alt="8" title="8" href="Controller?action=showopt&id=8" coords="1102,513,1176,562" shape="rect">
    <area  alt="7" title="7" href="Controller?action=showopt&id=7" coords="1176,513,1251,565" shape="rect">
    <area  alt="6" title="6" href="Controller?action=showopt&id=6" coords="1253,515,1325,565" shape="rect">
    <area  alt="5" title="5" href="Controller?action=showopt&id=5" coords="1387,560,1436,634" shape="rect">
    <area  alt="66" title="66" href="Controller?action=showopt&id=66" coords="889,879,962,931" shape="rect">
    <area  alt="65" title="65" href="Controller?action=showopt&id=65" coords="809,882,879,931" shape="rect">
    <area  alt="E2" title="E2" href="Controller?action=showopt&id=E2" coords="809,936,881,985" shape="rect">
    <area  alt="E1" title="E1" href="Controller?action=showopt&id=E1" coords="891,941,962,983" shape="rect">
    <area  alt="1" title="1" href="Controller?action=showopt&id=1" coords="1672,717,1730,762,1761,725,1705,678" shape="poly">
    <area  alt="2" title="2" href="Controller?action=showopt&id=2" coords="1639,630,1614,671,1672,713,1701,673" shape="poly">
    <area  alt="3" title="3" href="Controller?action=showopt&id=3" coords="1579,590,1550,636,1614,675,1635,631" shape="poly">
    <area  alt="4" title="4" href="Controller?action=showopt&id=4" coords="1507,556,1480,599,1546,630,1569,589" shape="poly">
    <area  alt="13" title="13" href="Controller?action=showopt&id=13" coords="654,584,681,627,739,594,718,547" shape="poly">
    <area  alt="14" title="14" href="Controller?action=showopt&id=14" coords="582,622,611,665,673,630,644,585" shape="poly">
    <area  alt="15" title="15" href="Controller?action=showopt&id=15" coords="578,624,516,667,545,710,607,667" shape="poly">
    <area  alt="16" title="16" href="Controller?action=showopt&id=16" coords="450,716,485,756,543,712,510,673" shape="poly">
</map>




















		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="js/bootstrap.js"></script>
		
	</body>
</html>