<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="">
	<jsp:include page="header.jsp">
		<jsp:param value="Plattegrond" name="title"/>
		<jsp:param value="Plattegrond jobbeurs" name="h2"/>
	</jsp:include>
	
	
	
	  <script
  src="https://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script type="text/javascript" src="js/jquery.maphilight.js"></script>
        <script type="text/javascript" src="js/imageMapResizer.js"></script>
	
	<!-- Image Map Generated by http://www.image-map.net/ -->
    <div class="container">
    <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<img src="img/Standplaatsen jobbeurs 2016-bedrijven-def-1.png" usemap="#image-map" id="hemis" class="img-responsive">

<map name="image-map" id="map1">
    <area  alt="64" id="64" title="64" href="Controller?action=showopt&id=64" coords="613,922,536,876" shape="rect">
    <area  alt="63" id="63" title="63" href="Controller?action=showopt&id=63" coords="615,872,689,922" shape="rect">
    <area  alt="62" id="62" title="62" href="Controller?action=showopt&id=62" coords="699,876,747,944" shape="rect">
    <area  alt="61" id="61" title="61" href="Controller?action=showopt&id=61" coords="697,951,749,1019" shape="rect">
    <area  alt="60" id="60" title="60" href="Controller?action=showopt&id=60" coords="726,1025,801,1070" shape="rect">
    <area  alt="59" id="59" title="59" href="Controller?action=showopt&id=59" coords="803,1025,873,1070" shape="rect">
    <area  alt="58" id="58" title="58" href="Controller?action=showopt&id=58" coords="879,1025,953,1068" shape="rect">
    <area  alt="57" id="57" title="57" href="Controller?action=showopt&id=57" coords="953,1027,1026,1068" shape="rect">
    <area  alt="56" id="56" title="56" href="Controller?action=showopt&id=56" coords="1026,953,1073,1019" shape="rect">
    <area  alt="55" id="55" title="55" href="Controller?action=showopt&id=55" coords="1024,876,1077,946" shape="rect">
    <area  alt="54" id="54" title="54" href="Controller?action=showopt&id=54" coords="1077,880,1156,927" shape="rect">
    <area  alt="53" id="53" title="53" href="Controller?action=showopt&id=53" coords="1160,880,1242,928" shape="rect">
    <area  alt="52" id="52" title="52" href="Controller?action=showopt&id=52" coords="1282,880,1364,926" shape="rect">
    <area  alt="51" id="51" title="51" href="Controller?action=showopt&id=51" coords="1368,878,1447,924" shape="rect">
    <area  alt="50" id="50" title="50" href="Controller?action=showopt&id=50" coords="1449,876,1531,926" shape="rect">
    <area  alt="49" id="49" title="49" href="Controller?action=showopt&id=49" coords="1490,780,1562,829" shape="rect">
    <area  alt="48" id="48" title="48" href="Controller?action=showopt&id=48" coords="1414,782,1490,829" shape="rect">
    <area  alt="47" id="47" title="47" href="Controller?action=showopt&id=47" coords="1341,780,1414,833" shape="rect">
    <area  alt="46" id="46" title="46" href="Controller?action=showopt&id=46" coords="1267,783,1335,834" shape="rect">
    <area  alt="45" id="45" title="45" href="Controller?action=showopt&id=45" coords="1193,780,1261,832" shape="rect">
    <area  alt="44" id="44" title="44" href="Controller?action=showopt&id=44" coords="1112,783,1187,832" shape="rect">
    <area  alt="43" id="43" title="43" href="Controller?action=showopt&id=43" coords="988,783,1061,830" shape="rect">
    <area  alt="42" id="42" title="42" href="Controller?action=showopt&id=42" coords="912,780,984,828" shape="rect">
    <area  alt="41" id="41" title="41" href="Controller?action=showopt&id=41" coords="838,780,908,828" shape="rect">
    <area  alt="40" id="40" title="40" href="Controller?action=showopt&id=40" coords="763,780,834,828" shape="rect">
    <area  alt="39" id="39" title="39" href="Controller?action=showopt&id=39" coords="685,780,759,829" shape="rect">
    <area  alt="38" id="38" title="38" href="Controller?action=showopt&id=38" coords="615,778,683,832" shape="rect">
    <area  alt="37" id="37" title="37" href="Controller?action=showopt&id=37" coords="613,714,685,763" shape="rect">
    <area  alt="36" id="36" title="36" href="Controller?action=showopt&id=36" coords="689,713,763,761" shape="rect">
    <area  alt="35" id="35" title="35" href="Controller?action=showopt&id=35" coords="765,714,836,763" shape="rect">
    <area  alt="34" id="34" title="34" href="Controller?action=showopt&id=34" coords="840,712,912,764" shape="rect">
    <area  alt="33" id="33" title="33" href="Controller?action=showopt&id=33" coords="914,714,984,762" shape="rect">
    <area  alt="32" id="32" title="32" href="Controller?action=showopt&id=32" coords="988,712,1061,763" shape="rect">
    <area  alt="31" id="31" title="31" href="Controller?action=showopt&id=31" coords="1114,714,1187,761" shape="rect">
    <area  alt="30" id="30" title="30" href="Controller?action=showopt&id=30" coords="1189,714,1263,762" shape="rect">
    <area  alt="29" id="29" title="29" href="Controller?action=showopt&id=29" coords="1263,714,1337,763" shape="rect">
    <area  alt="28" id="28" title="28" href="Controller?action=showopt&id=28" coords="1341,714,1412,763" shape="rect">
    <area  alt="27" id="27" title="27" href="Controller?action=showopt&id=27" coords="1416,713,1486,761" shape="rect">
    <area  alt="26" id="26" title="26" href="Controller?action=showopt&id=26" coords="1488,713,1564,763" shape="rect">
    <area  alt="25" id="25" title="25" href="Controller?action=showopt&id=25" coords="1261,609,1333,656" shape="rect">
    <area  alt="24" id="24" title="24" href="Controller?action=showopt&id=24" coords="1187,606,1257,659" shape="rect">
    <area  alt="23" id="23" title="23" href="Controller?action=showopt&id=23" coords="1110,605,1183,654" shape="rect">
    <area  alt="22" id="22" title="22" href="Controller?action=showopt&id=22" coords="1001,607,1075,657" shape="rect">
    <area  alt="21" id="21" title="21" href="Controller?action=showopt&id=21" coords="922,609,997,654" shape="rect">
    <area  alt="20" id="20" title="20" href="Controller?action=showopt&id=20" coords="848,606,920,658" shape="rect">
    <area  alt="19" id="19" title="19" href="Controller?action=showopt&id=19" coords="1723,839,1775,907" shape="rect">
    <area  alt="18" id="18" title="18" href="Controller?action=showopt&id=18" coords="1721,762,1779,834" shape="rect">
    <area  alt="17" id="17" title="17" href="Controller?action=showopt&id=17" coords="435,770,491,842" shape="rect">
    <area  alt="12" id="12" title="12" href="Controller?action=showopt&id=12" coords="759,565,809,635" shape="rect">
    <area  alt="11" id="11" title="11" href="Controller?action=showopt&id=11" coords="875,512,951,563" shape="rect">
    <area  alt="10" id="10" title="10" href="Controller?action=showopt&id=10" coords="953,514,1024,565" shape="rect">
    <area  alt="09" id="09" title="09" href="Controller?action=showopt&id=09" coords="1028,513,1098,562" shape="rect">
    <area  alt="08" id="08" title="08" href="Controller?action=showopt&id=08" coords="1102,513,1176,562" shape="rect">
    <area  alt="07" id="07" title="07" href="Controller?action=showopt&id=07" coords="1176,513,1251,565" shape="rect">
    <area  alt="06" id="06" title="06" href="Controller?action=showopt&id=06" coords="1253,515,1325,565" shape="rect">
    <area  alt="05" id="05" title="05" href="Controller?action=showopt&id=05" coords="1387,560,1436,634" shape="rect">
    <area  alt="66" id="66" title="66" href="Controller?action=showopt&id=66" coords="889,879,962,931" shape="rect">
    <area  alt="65" id="65" title="65" href="Controller?action=showopt&id=65" coords="809,882,879,931" shape="rect">
    <area  alt="E2" id="E2" title="E2" href="Controller?action=showopt&id=E2" coords="809,936,881,985" shape="rect">
    <area  alt="E1" id="E1" title="E1" href="Controller?action=showopt&id=E1" coords="891,941,962,983" shape="rect">
    <area  alt="01" id="01" title="01" href="Controller?action=showopt&id=01" coords="1672,717,1730,762,1761,725,1705,678" shape="poly">
    <area  alt="02" id="02" title="02" href="Controller?action=showopt&id=02" coords="1639,630,1614,671,1672,713,1701,673" shape="poly">
    <area  alt="03" id="03" title="03" href="Controller?action=showopt&id=03" coords="1579,590,1550,636,1614,675,1635,631" shape="poly">
    <area  alt="04" id="04" title="04" href="Controller?action=showopt&id=04" coords="1507,556,1480,599,1546,630,1569,589" shape="poly">
    <area  alt="13" id="13" title="13" href="Controller?action=showopt&id=13" coords="654,584,681,627,739,594,718,547" shape="poly">
    <area  alt="14" id="14" title="14" href="Controller?action=showopt&id=14" coords="582,622,611,665,673,630,644,585" shape="poly">
    <area  alt="15" id="15" title="15" href="Controller?action=showopt&id=15" coords="578,624,516,667,545,710,607,667" shape="poly">
    <area  alt="16" id="16" title="16" href="Controller?action=showopt&id=16" coords="450,716,485,756,543,712,510,673" shape="poly">

</map>












<img src="img/standplaatsen-atrium-crop.png" usemap="#image-map-atrium"id="atrium" class="img-responsive">

<map name="image-map-atrium" id="atrium-map">
    <area target="" alt="A01" id="A01" title="A01" href="Controller?action=showopt&id=A01" coords="1123,370,1183,468" shape="rect">
    <area target="" alt="A02" id="A02" title="A02" href="Controller?action=showopt&id=A02" coords="1127,473,1183,560" shape="rect">
    <area target="" alt="A03" id="A03" title="A03" href="Controller?action=showopt&id=A03" coords="1020,562,1123,615" shape="rect">
    <area target="" alt="A04" id="A04" title="A04" href="Controller?action=showopt&id=A04" coords="908,561,1012,615" shape="rect">
    <area target="" alt="A05" id="A05" title="A05" href="Controller?action=showopt&id=A05" coords="802,561,903,615" shape="rect">
    <area target="" alt="A06" id="A06" title="A06" href="Controller?action=showopt&id=A06" coords="693,559,794,615" shape="rect">
    <area target="" alt="A07" id="A07" title="A07" href="Controller?action=showopt&id=A07" coords="589,560,687,618" shape="rect">
    <area target="" alt="A08" id="A08" title="A08" href="Controller?action=showopt&id=A08" coords="489,560,584,616" shape="rect">
    <area target="" alt="A09" id="A09" title="A09" href="Controller?action=showopt&id=A09" coords="440,470,496,555" shape="rect">
    <area target="" alt="A10" id="A10" title="A10" href="Controller?action=showopt&id=A10" coords="443,372,493,461" shape="rect">
    <area target="" alt="A11" id="A11" title="A11" href="Controller?action=showopt&id=A11" coords="757,373,810,473" shape="rect">
    <area target="" alt="A12" id="A12" title="A12" href="Controller?action=showopt&id=A12" coords="817,373,875,473" shape="rect">
</map>
</div></div></div>



<c:if test="${errors!=null}">
			<div>
				<ul>
					<c:forEach var="error" items="${errors}">
						<li>${error}</li>
					</c:forEach>
				</ul>
			</div>
</c:if>


<p hidden class="">list of items</p>


 <script type="text/javascript">



    jQuery(function()
                            {
             jQuery('#hemis').maphilight();
             jQuery('#atrium').maphilight();
                            });

 
    var ImageMap = function (map, img) {
            var n,
                areas = map.getElementsByTagName('area'),
                len = areas.length,
                coords = [],
                previousWidth = 2339;
            for (n = 0; n < len; n++) {
                coords[n] = areas[n].coords.split(',');
            }
            this.resize = function () {
                var n, m, clen,
                    x = img.offsetWidth / previousWidth;
                for (n = 0; n < len; n++) {
                    clen = coords[n].length;
                    for (m = 0; m < clen; m++) {
                        coords[n][m] *= x;
                    }
                    areas[n].coords = coords[n].join(',');
                }
                previousWidth = img.offsetWidth;



/**
*red
*/
    $(function () {
        var data = {};
        $('.map').maphilight();
        data.alwaysOn = true;
        data.fillColor = 'ff0000';
        data.fillOpacity = '0.6';
        $('.imgmaphigh').data('maphilight', data).trigger('alwaysOn.maphilight');    
    });


/**
*green
*/




    $(function () {
        var data = {};
        $('.map').maphilight();
        data.alwaysOn = true;
        data.fillColor = '00ff00';
        data.fillOpacity = '0.6';
        $('.mine').data('maphilight', data).trigger('alwaysOn.maphilight'); 
        
    });






                return true;
            };
            window.onresize = this.resize;
        },
        imageMap = new ImageMap(document.getElementById('map1'), document.getElementById('hemis'));
    imageMap.resize();
























    $(function () {
    var data = {};
    $('.map').maphilight();
    data.alwaysOn = true;
    data.fillColor = 'ff0000';
    data.fillOpacity = '0.6';   /*
    $('#12').data('maphilight', data).trigger('alwaysOn.maphilight'); 
    $('#31').data('maphilight', data).trigger('alwaysOn.maphilight'); 
    $('#33').data('maphilight', data).trigger('alwaysOn.maphilight'); 
    $('#58').data('maphilight', data).trigger('alwaysOn.maphilight'); */
});


    $(function () {
    var data = {};
    $('.map').maphilight();
    data.alwaysOn = true;
    data.fillColor = '00ff00';
    data.fillOpacity = '0.6';
    $('.mine').data('maphilight', data).trigger('alwaysOn.maphilight'); 
    
});






</script>











		
	</body>
</html>